<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Remitter.Client\Remitter.Client.csproj" />
    <ProjectReference Include="..\Remitter.Domain\Remitter.Domain.csproj" />
  </ItemGroup>
</Project>
